In [1]:
import numpy as np
import struct
import os

In [2]:
mnist_dir = "mnist_data/"
train_data_dir = "train-images.idx3-ubyte"
train_label_dir = "train-labels.idx1-ubyte"
test_data_dir = "t10k-images.idx3-ubyte"
test_label_dir = "t10k-labels.idx1-ubyte"
k = 10
iters = 500
alpha = 0.5

In [3]:
from data_process import load_mnist, load_data
from train import train
from evaluate import predict, cal_accuracy
from data_process import data_convert
from softmax_regression import softmax_regression

In [4]:
train_images, train_labels, test_images, test_labels = load_data(mnist_dir, train_data_dir, train_label_dir, test_data_dir, test_label_dir)
print("Got data. ") 

Loading MNIST data from files...
mnist_data/train-images.idx3-ubyte
Load images from mnist_data/train-images.idx3-ubyte, number: 60000, data shape: (60000, 784)
Load images from mnist_data/train-labels.idx1-ubyte, number: 60000, data shape: (60000, 1)
Load images from mnist_data/t10k-images.idx3-ubyte, number: 10000, data shape: (10000, 784)
Load images from mnist_data/t10k-labels.idx1-ubyte, number: 10000, data shape: (10000, 1)
Got data. 


In [64]:
test_labels.shape

(10000, 1)

In [66]:
test_labels.count()

AttributeError: 'numpy.ndarray' object has no attribute 'count'

In [5]:
m, n = train_images.shape #(60000,784),28*28 image
    # data processing
x, y = data_convert(train_images, train_labels, m, k) # x:[m,n], y:[1,m]

In [6]:
theta = np.random.rand(k, n)

In [7]:
alpha = 0.5
iters = 5

In [8]:
x.shape

(60000, 784)

In [62]:
len(y)

10

In [9]:
theta

array([[0.07424628, 0.38154347, 0.26951832, ..., 0.47206111, 0.9672288 ,
        0.57337014],
       [0.5479062 , 0.59370349, 0.80877965, ..., 0.24648344, 0.60641112,
        0.04551493],
       [0.5408912 , 0.92150979, 0.39939823, ..., 0.8304639 , 0.58936789,
        0.02945599],
       ...,
       [0.23658064, 0.42276627, 0.31149386, ..., 0.91723681, 0.86095962,
        0.98105114],
       [0.63619874, 0.95716435, 0.95780243, ..., 0.82380388, 0.29380801,
        0.47599269],
       [0.33532218, 0.50577762, 0.84133385, ..., 0.72934348, 0.58070239,
        0.36635324]])

In [10]:
theta.sum(axis =1)

array([386.57437606, 399.96648625, 391.74730992, 397.83927369,
       389.19061953, 379.45491965, 399.35175132, 390.4435835 ,
       389.6258913 , 404.01640858])

In [8]:
theta = softmax_regression(theta, x, y, 10, alpha)

100%|██████████| 10/10 [00:06<00:00,  1.56it/s]


In [10]:
theta.shape

(10, 784)

In [25]:
t =[2 for i in range(theta.shape[1])]

In [26]:
t = np.array(t)

In [28]:
t

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,

In [27]:
t.shape

(784,)

In [29]:
t1 = [t for i in range(len(theta))]

In [32]:
t1 = np.array(t1)

In [34]:
t1

array([[2, 2, 2, ..., 2, 2, 2],
       [2, 2, 2, ..., 2, 2, 2],
       [2, 2, 2, ..., 2, 2, 2],
       ...,
       [2, 2, 2, ..., 2, 2, 2],
       [2, 2, 2, ..., 2, 2, 2],
       [2, 2, 2, ..., 2, 2, 2]])

In [16]:
theta

array([[0.63438628, 0.37207618, 0.94363452, ..., 0.32115894, 0.94064714,
        0.94354456],
       [0.78220506, 0.30741949, 0.81259823, ..., 0.04427103, 0.37236462,
        0.92509876],
       [0.21492065, 0.22100652, 0.55424125, ..., 0.38916846, 0.30760314,
        0.32381088],
       ...,
       [0.05037117, 0.28071692, 0.88310884, ..., 0.76590404, 0.42920235,
        0.24740923],
       [0.18131756, 0.24079299, 0.44037936, ..., 0.24528562, 0.01491196,
        0.63088476],
       [0.4808894 , 0.20161865, 0.93994656, ..., 0.21943474, 0.35883562,
        0.42227015]])

In [17]:
th = theta / t

In [18]:
th

array([[0.31719314, 0.18603809, 0.47181726, ..., 0.16057947, 0.47032357,
        0.47177228],
       [0.39110253, 0.15370974, 0.40629911, ..., 0.02213551, 0.18618231,
        0.46254938],
       [0.10746032, 0.11050326, 0.27712063, ..., 0.19458423, 0.15380157,
        0.16190544],
       ...,
       [0.02518559, 0.14035846, 0.44155442, ..., 0.38295202, 0.21460118,
        0.12370461],
       [0.09065878, 0.1203965 , 0.22018968, ..., 0.12264281, 0.00745598,
        0.31544238],
       [0.2404447 , 0.10080932, 0.46997328, ..., 0.10971737, 0.17941781,
        0.21113508]])

In [12]:
theta.sum(axis = 1)

array([392.10266775, 396.12069157, 398.70856128, 395.09896797,
       388.38829766, 379.09854868, 399.50972354, 390.04323243,
       390.7986539 , 398.34127503])

In [19]:
res = theta@x.T
result = x@theta.T

In [20]:
res

array([[68.75691835, 89.7511348 , 57.40485156, ..., 56.09261482,
        60.92985601, 55.5988342 ],
       [68.69013397, 74.52706398, 51.81378154, ..., 55.64346038,
        54.30442063, 58.09630213],
       [73.63897091, 79.20888994, 52.30928587, ..., 56.56440467,
        57.90647861, 59.72752578],
       ...,
       [70.5086886 , 85.25024895, 47.10884703, ..., 55.54253832,
        55.39250912, 61.43949369],
       [71.65221902, 79.27159441, 55.98664122, ..., 59.06821218,
        50.20835717, 61.06174536],
       [70.83595907, 78.93212025, 53.70215102, ..., 61.21470934,
        57.24937012, 59.56785929]])

In [21]:
t1 = np.argmax(res, axis = 0)

In [22]:
t2 = y.argmax(axis = 0)

In [53]:
abs(t1-t2).sum()/len(t2)

0.6547833333333334

In [58]:
t1[-10:]

array([9, 2, 8, 5, 1, 8, 3, 5, 6, 9], dtype=int64)

In [59]:
t2[-10:]

array([9, 2, 9, 5, 1, 8, 3, 5, 6, 8], dtype=int64)

In [15]:
result.argmax(axis = 1)

array([6, 6, 6, ..., 6, 6, 6], dtype=int64)

In [23]:
res_exp = np.exp(res)

In [24]:
res_exp.argmax(axis=0) #预测结果

array([2, 0, 4, ..., 9, 6, 5], dtype=int64)

In [71]:
pos = np.argmax(y,axis=0)

In [72]:
pos #lable

array([5, 0, 4, ..., 5, 6, 8], dtype=int64)

In [73]:
label_pos =[(pos[x],x) for x in range(len(pos))]

In [74]:
res_exp.shape

(10, 60000)

In [75]:
f = [-np.log(res_exp[x]) for x in label_pos ]

In [76]:
len(f)

60000

In [77]:
cost = sum(f)/len(f)

In [78]:
cost

6.389791752747614

In [79]:
res_exp.shape

(10, 60000)

In [80]:
y.shape

(10, 60000)

In [99]:
x.shape

(60000, 784)

In [100]:
res_exp.shape

(10, 60000)

In [101]:
grad = np.dot(x.T,(res_exp-y).T)

In [85]:
grad.shape

(784, 10)

In [103]:
grad.shape

(784, 10)

In [28]:
grad.sum()

7.491962605854496e-11

In [107]:
y.shape

(10, 60000)

In [109]:
res_exp.shape

(10, 60000)

In [110]:
res_exp.sum(axis = 0)

array([1., 1., 1., ..., 1., 1., 1.])

In [113]:
type(y)

numpy.ndarray

In [114]:
(res_exp-y).sum()

-3.183231456205249e-12

: 

In [38]:
grad.shape

(784, 10)

In [41]:
grad.sum(axis=0)

array([1501923.53270179, -450297.50273554, -539266.97118916,
        501582.85325061, 1451963.26441378, -604405.46602881,
       -431703.88330356, -411868.325423  , -334171.67492494,
       -683755.82676117])

In [36]:
theta.shape

(10, 784)

In [42]:
x.shape

(784, 60000)

In [31]:
x.shape[1]

60000

In [49]:
tmp = 0.5*1/x.shape[1]*grad.T

In [44]:
theta.sum(axis = 1)

array([365.13259488, 371.02715268, 368.06232508, 369.64135242,
       398.48317005, 438.02961674, 401.63110489, 373.74562713,
       371.45659708, 416.23492552])

In [45]:
theta = theta+(0.5*1/x.shape[1])*grad.T

In [46]:
theta.sum(axis = 1)

array([359.31698983, 367.24508477, 362.09463022, 364.29817239,
       400.68677316, 450.92934054, 403.75920472, 370.36433099,
       368.03583988, 426.71409997])

In [133]:
(res_exp-y).T.shape

(60000, 10)

In [123]:
y.shape

(10, 60000)

In [83]:
y.argmax(axis = 0)

array([5, 0, 4, ..., 5, 6, 8], dtype=int64)

In [81]:
res.argmax(axis=0)

array([7, 0, 4, ..., 4, 0, 8], dtype=int64)

In [44]:
len(pos_for_loss)

60000

In [46]:
res_exp

array([[3.00813471e-04, 4.49729172e-01, 5.03115640e-02, ...,
        1.88332139e-03, 4.73408532e-01, 2.20263294e-03],
       [6.94554752e-05, 2.34683481e-03, 3.34752769e-02, ...,
        2.28143754e-03, 2.21119592e-02, 1.47044289e-03],
       [2.33911642e-02, 6.27222721e-03, 1.14095703e-02, ...,
        2.44989002e-03, 7.66200114e-04, 8.39644383e-06],
       ...,
       [9.36143268e-01, 2.83927515e-01, 3.30092548e-03, ...,
        2.42613872e-01, 4.65059441e-01, 5.78126449e-05],
       [3.24547441e-03, 1.35902875e-01, 3.60131206e-01, ...,
        1.79017926e-02, 8.26714622e-03, 9.95708294e-01],
       [2.03848539e-05, 3.77353396e-02, 5.15692762e-04, ...,
        1.24454559e-02, 7.78425002e-03, 4.45963602e-04]])

In [68]:
res_exp[pos_for_loss[0]]

0.031606828287051615

In [70]:
pos_for_loss[0]

(5, 0)

In [71]:
res_exp.argmax(axis=0)

array([7, 0, 4, ..., 4, 0, 8], dtype=int64)

In [40]:
f = res_exp[pos_for_loss]

MemoryError: Unable to allocate 53.6 GiB for an array with shape (60000, 2, 60000) and data type float64

In [130]:
f = []
for col in range(res.shape[1]):
    f.append(res_exp[pos,col])

KeyboardInterrupt: 